export const GET_RECIPES = 'GET_RECIPES';
export const GET_TYPES_OF_DIET = 'GET_TYPES_OF_DIET';
export const GET_RECIPES_BY_NAME = 'GET_RECIPES_BY_NAME';
export const POST_RECIPES = 'POST_RECIPES';
export const FILTER_BY_DIET = 'FILTER_BY_DIET';
export const FILTER_CREATED = 'FILTER_CREATED';
export const ORDER_BY_NAME = 'ORDER_BY_NAME';
export const ORDER_BY_SCORE = 'ORDER_BY_SCORE';
export const GET_DETAIL = 'GET_DETAIL';

